/**
 * Slot type definitions
 *
 * Slots are the bookable inventory generated from pricing rules. Each slot
 * captures a price snapshot at creation time.
 */

import type { SlotStatus } from "./enums";

/**
 * Slot entity.
 *
 * `price` is typed as `string` because the backend serializes the Prisma
 * `Decimal` column to a JSON string (e.g. "500.00"). Format with
 * `Number(price)` before rendering.
 */
export interface Slot {
  id: string;
  tenantId: string;
  courtId: string;
  courtName?: string;
  pricingRuleId?: string;
  price: string; // Decimal serialized as string
  date: string; // YYYY-MM-DD
  startTime: string; // HH:mm
  endTime: string; // HH:mm
  status: SlotStatus;
  heldAt?: string | null;
  heldBy?: string | null;
  heldUntil?: string | null;
  createdAt: string;
  updatedAt: string;
}

/**
 * Generate slots request payload — omit courtId to generate for all courts
 */
export interface GenerateSlotsDto {
  courtId?: string;
  startDate: string; // YYYY-MM-DD
  endDate: string; // YYYY-MM-DD
}

/**
 * Result of a slot generation run
 */
export interface SlotGenerationResult {
  generated: number;
  skipped: number;
  errors: string[];
}

/**
 * Block slot request payload
 */
export interface BlockSlotDto {
  reason: string;
}

/**
 * Paginated slot list response
 */
export interface SlotListResponse {
  data: Slot[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

/**
 * Query parameters for filtering slots
 */
export interface QuerySlotsParams {
  courtId?: string;
  status?: SlotStatus;
  date?: string; // YYYY-MM-DD
  page?: number;
  limit?: number;
}

/**
 * Cleanup result
 */
export interface CleanupSlotsResult {
  deleted: number;
}

/**
 * Tenant slot-generation settings
 */
export interface SlotSettings {
  /** ISO weekday ints, 0 = Sunday … 6 = Saturday (default [5, 6] = Fri + Sat) */
  weekendDays: number[];
  timezone: string;
  autoGenerateEnabled: boolean;
  autoGenerateDaysAhead: number;
}

export interface UpdateSlotSettingsDto {
  weekendDays?: number[];
  autoGenerateEnabled?: boolean;
  autoGenerateDaysAhead?: number;
}

/**
 * Holiday calendar entry
 */
export interface Holiday {
  id: string;
  tenantId: string;
  date: string; // YYYY-MM-DD
  name: string;
}

export interface CreateHolidayDto {
  date: string; // YYYY-MM-DD
  name: string;
}

/**
 * Names for ISO weekday indices, used to render weekend-day labels
 */
export const WEEKDAY_LABELS = [
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
] as const;
