import { Injectable, Logger } from '@nestjs/common';
import { Cron } from '@nestjs/schedule';
import { SlotsService } from './slots.service';

/**
 * SlotsScheduler — automatic slot generation.
 *
 * Runs hourly (off the :00 mark to avoid thundering-herd load spikes) and
 * fills the next `autoGenerateDaysAhead` days for every tenant that has
 * auto-generation enabled. The run is idempotent: generation only fills
 * dates that have no slots yet, so running every hour is harmless and makes
 * the job insensitive to per-tenant timezone differences (each tenant's
 * window is computed from "today" in ITS timezone at run time).
 */
@Injectable()
export class SlotsScheduler {
  private readonly logger = new Logger(SlotsScheduler.name);

  constructor(private readonly slotsService: SlotsService) {}

  @Cron('17 * * * *')
  async autoGenerate(): Promise<void> {
    const summaries = await this.slotsService.runAutoGeneration();

    for (const { tenantId, result } of summaries) {
      if (result.errors.length > 0) {
        this.logger.error(
          `Auto-generation failed for tenant ${tenantId}: ${result.errors.join('; ')}`,
        );
      } else if (result.generated > 0) {
        this.logger.log(
          `Auto-generation for tenant ${tenantId}: created ${result.generated} slots`,
        );
      }
      // generated === 0 means the window is already filled — nothing to log
    }
  }
}
