/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import {
  Injectable,
  NotFoundException,
  BadRequestException,
  ConflictException,
} from '@nestjs/common';
import { PrismaService } from '@src/prisma/prisma.service';
import {
  Slot,
  PricingRule,
  SlotStatus,
  DayType,
  Prisma,
  PrismaClient,
} from '../../../generated/prisma/client';
import { GenerateSlotsDto } from './dto/generate-slots.dto';
import { QuerySlotsDto } from './dto/query-slots.dto';
import { UpdateSlotSettingsDto } from './dto/slot-settings.dto';
import { CreateHolidayDto } from './dto/holiday.dto';

// ============================================================================
// Type Definitions
// ============================================================================

/**
 * Slot shaped for API responses.
 * Prisma's `Decimal` price and `@db.Date`/`@db.Time` values are serialized to
 * strings (price, date as YYYY-MM-DD, times as HH:mm) to stay symmetric with
 * the Pricing module's wire format.
 */
export interface SlotResponse {
  id: string;
  tenantId: string;
  courtId: string;
  courtName?: string;
  pricingRuleId?: string;
  price: string;
  date: string;
  startTime: string;
  endTime: string;
  status: SlotStatus;
  heldAt?: Date | null;
  heldBy?: string | null;
  heldUntil?: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Paginated slot list response
 */
export interface SlotListResponse {
  data: SlotResponse[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

/**
 * Result returned by slot generation.
 * `generated` = rows actually inserted; `skipped` = rows that already existed
 * (deduped by the unique constraint `no_duplicate_slot_generation`).
 */
export interface SlotGenerationResult {
  generated: number;
  skipped: number;
  errors: string[];
}

/**
 * Tenant slot-generation settings
 */
export interface SlotSettingsResponse {
  weekendDays: number[];
  timezone: string;
  autoGenerateEnabled: boolean;
  autoGenerateDaysAhead: number;
}

/**
 * Holiday calendar entry
 */
export interface HolidayResponse {
  id: string;
  tenantId: string;
  date: string;
  name: string;
}

/**
 * Prisma transaction client type (for audit-log writes inside $transaction)
 */
type PrismaTransaction = Omit<
  PrismaClient,
  '$connect' | '$disconnect' | '$on' | '$transaction' | '$use' | '$extends'
>;

/**
 * Default hold window (in minutes) when a customer starts checkout.
 */
const DEFAULT_HOLD_MINUTES = 15;

/**
 * Maximum number of days that can be generated in a single request.
 * Guards against accidentally materializing huge slot ranges.
 */
const MAX_GENERATE_RANGE_DAYS = 90;

/**
 * Allowed slot intervals (minutes) a court can be configured with.
 * Guard here as well as in the courts module so bad data can never
 * produce zero-length or nonsensical slots.
 */
const ALLOWED_SLOT_INTERVALS = [30, 45, 60, 90, 120];

/**
 * Default weekend when a tenant has no valid `weekendDays` set:
 * Friday (5) + Saturday (6) — the Bangladesh weekend.
 */
const DEFAULT_WEEKEND_DAYS = [5, 6];

/**
 * Map of short weekday names (as produced by Intl 'en-US') to ISO day numbers.
 */
const WEEKDAY_NAME_TO_INDEX: Record<string, number> = {
  Sun: 0,
  Mon: 1,
  Tue: 2,
  Wed: 3,
  Thu: 4,
  Fri: 5,
  Sat: 6,
};

// ============================================================================
// Service
// ============================================================================

@Injectable()
export class SlotsService {
  constructor(private readonly prisma: PrismaService) {}

  // --------------------------------------------------------------------------
  // Generation
  // --------------------------------------------------------------------------

  /**
   * Generate slots from pricing rules over a date range.
   *
   * For each court (one court, or every court when `dto.courtId` is omitted)
   * and each date in the range the service:
   *   1. Determines the day type using the TENANT's weekend days and holiday
   *      calendar, evaluated in the tenant's timezone (default BD: Fri+Sat).
   *   2. Loads matching, non-deleted pricing rules for that court + day type.
   *   3. Expands each rule's time range into fixed-interval slots (the court's
   *      `slotIntervalMinutes`), snapshotting the rule's price onto every slot.
   *
   * MIXED-INTERVAL SAFETY RULE: generation only fills dates that have ZERO
   * existing slots for the court. This prevents overlapping tiles when a
   * court's interval is changed later (the unique constraint only catches
   * identical start times, not overlaps). `skipped` reports the slots that
   * were not created because their date was already populated.
   *
   * Concurrency is still enforced at the DB level: `createMany` with
   * `skipDuplicates` rides on the `@@unique([courtId, date, startTime])`
   * constraint, so re-running generation is idempotent and race-safe.
   *
   * @param tenantId - Tenant ID from context
   * @param dto - optional courtId + inclusive startDate/endDate (YYYY-MM-DD);
   *              omitted courtId = all non-deleted courts of the tenant
   * @param userId - User ID triggering generation (for audit); omitted when
   *                 invoked by the auto-generation scheduler
   */
  async generateSlots(
    tenantId: string,
    dto: GenerateSlotsDto,
    userId?: string,
  ): Promise<SlotGenerationResult> {
    const { courtId, startDate, endDate } = dto;

    const start = this.parseDateString(startDate);
    const end = this.parseDateString(endDate);

    if (Number.isNaN(start.getTime()) || Number.isNaN(end.getTime())) {
      throw new BadRequestException('Invalid date format');
    }

    if (start > end) {
      throw new BadRequestException('Start date must be on or before end date');
    }

    const daySpan = Math.floor(
      (end.getTime() - start.getTime()) / (24 * 60 * 60 * 1000),
    );
    if (daySpan > MAX_GENERATE_RANGE_DAYS) {
      throw new BadRequestException(
        `Date range cannot exceed ${MAX_GENERATE_RANGE_DAYS} days`,
      );
    }

    // Resolve target courts (scoped to tenant, not soft-deleted)
    const courts = await this.prisma.court.findMany({
      where: courtId
        ? { id: courtId, tenantId, deletedAt: null }
        : { tenantId, deletedAt: null },
      orderBy: { name: 'asc' },
    });
    if (courts.length === 0) {
      if (courtId) {
        throw new NotFoundException(
          'Court not found or does not belong to this organization',
        );
      }
      throw new BadRequestException(
        'No courts found for this organization. Add a court first.',
      );
    }

    // Tenant context drives day-type classification
    const tenant = await this.prisma.tenant.findUnique({
      where: { id: tenantId },
      select: { timezone: true, weekendDays: true },
    });
    if (!tenant) {
      throw new NotFoundException('Tenant not found');
    }
    const weekendDays = this.parseWeekendDays(tenant.weekendDays);
    const timezone = tenant.timezone || 'Asia/Dhaka';

    // Tenant holidays inside the range (dates classified as Holiday)
    const holidays = await this.prisma.holiday.findMany({
      where: { tenantId, date: { gte: start, lte: end } },
      select: { date: true },
    });
    const holidayDates = new Set(
      holidays.map((h) => this.formatDateToYYYYMMDD(h.date)),
    );

    const days = this.eachDay(start, end);

    const aggregate: SlotGenerationResult = {
      generated: 0,
      skipped: 0,
      errors: [],
    };

    for (const court of courts) {
      try {
        const result = await this.generateForCourt(
          tenantId,
          court,
          days,
          startDate,
          endDate,
          weekendDays,
          timezone,
          holidayDates,
          userId,
        );
        aggregate.generated += result.generated;
        aggregate.skipped += result.skipped;
      } catch (error) {
        aggregate.errors.push(
          `Court "${court.name}": ${(error as Error).message}`,
        );
      }
    }

    return aggregate;
  }

  /**
   * Auto-generation entry point for the scheduler. Fills the next
   * `daysAhead` days (from today in the tenant's timezone) for every court of
   * every tenant that has auto-generation enabled. Idempotent thanks to the
   * empty-date rule, so frequent runs are harmless.
   *
   * @returns one summary line per processed tenant (for logging)
   */
  async runAutoGeneration(): Promise<
    Array<{ tenantId: string; result: SlotGenerationResult }>
  > {
    const tenants = await this.prisma.tenant.findMany({
      where: { autoGenerateEnabled: true, deletedAt: null },
      select: {
        id: true,
        timezone: true,
        autoGenerateDaysAhead: true,
        tenantMembers: { select: { userId: true }, take: 1 },
      },
    });

    const summaries: Array<{ tenantId: string; result: SlotGenerationResult }> =
      [];

    for (const tenant of tenants) {
      const today = this.todayInTimezone(tenant.timezone || 'Asia/Dhaka');
      const endDate = this.addDaysToDateString(
        today,
        tenant.autoGenerateDaysAhead,
      );
      // Attribute the automated run to the tenant's first member for the
      // audit trail (no HTTP user exists in a cron context).
      const auditUserId = tenant.tenantMembers[0]?.userId;
      try {
        const result = await this.generateSlots(
          tenant.id,
          { startDate: today, endDate },
          auditUserId,
        );
        summaries.push({ tenantId: tenant.id, result });
      } catch (error) {
        summaries.push({
          tenantId: tenant.id,
          result: {
            generated: 0,
            skipped: 0,
            errors: [(error as Error).message],
          },
        });
      }
    }

    return summaries;
  }

  /**
   * Core generation for a single court. Builds every slot payload up front,
   * skips dates that already have slots, then inserts in one statement.
   */
  private async generateForCourt(
    tenantId: string,
    court: { id: string; name: string; slotIntervalMinutes: number },
    days: Date[],
    startDate: string,
    endDate: string,
    weekendDays: number[],
    timezone: string,
    holidayDates: Set<string>,
    userId?: string,
  ): Promise<{ generated: number; skipped: number }> {
    const interval = ALLOWED_SLOT_INTERVALS.includes(court.slotIntervalMinutes)
      ? court.slotIntervalMinutes
      : 60;

    // Fetch pricing rules once per distinct day type in the range
    const dayTypesInUse = new Set(
      days.map((d) => this.getDayType(d, weekendDays, holidayDates, timezone)),
    );
    const rulesByDayType = new Map<DayType, PricingRule[]>();
    for (const dayType of dayTypesInUse) {
      rulesByDayType.set(
        dayType,
        await this.prisma.pricingRule.findMany({
          where: {
            tenantId,
            courtId: court.id,
            dayType,
            deletedAt: null,
          },
        }),
      );
    }

    // Dates already populated for this court are skipped entirely
    // (MIXED-INTERVAL SAFETY RULE — see generateSlots doc)
    const existing = await this.prisma.slot.findMany({
      where: {
        tenantId,
        courtId: court.id,
        date: { gte: days[0], lte: days[days.length - 1] },
      },
      select: { date: true },
      distinct: ['date'],
    });
    const populatedDates = new Set(
      existing.map((e) => this.formatDateToYYYYMMDD(e.date)),
    );

    const slotsToCreate: Prisma.SlotCreateManyInput[] = [];
    let skipped = 0;

    for (const date of days) {
      const dayType = this.getDayType(
        date,
        weekendDays,
        holidayDates,
        timezone,
      );
      const rules = rulesByDayType.get(dayType) ?? [];

      if (populatedDates.has(this.formatDateToYYYYMMDD(date))) {
        // Count what would have been generated so `skipped` stays honest
        for (const rule of rules) {
          skipped += this.generateIntervalSlots(
            rule.startTime,
            rule.endTime,
            interval,
          ).length;
        }
        continue;
      }

      for (const rule of rules) {
        for (const { startTime, endTime } of this.generateIntervalSlots(
          rule.startTime,
          rule.endTime,
          interval,
        )) {
          slotsToCreate.push({
            tenantId,
            courtId: court.id,
            pricingRuleId: rule.id,
            price: rule.price, // snapshot from pricing rule
            date,
            startTime,
            endTime,
            status: SlotStatus.Available,
          });
        }
      }
    }

    const totalAttempted = slotsToCreate.length;

    const generated = await this.prisma.$transaction(async (tx) => {
      let inserted = 0;
      if (totalAttempted > 0) {
        const result = await tx.slot.createMany({
          data: slotsToCreate,
          skipDuplicates: true,
        });
        inserted = result.count;
      }

      // Audit only when an HTTP user triggered the run (cron runs are
      // attributed to the tenant's first member, or skipped if none exists)
      if (userId) {
        await this.createAuditLog(tx, {
          tenantId,
          userId,
          entityType: 'Slot',
          entityId: court.id,
          action: 'Create',
          newValue: {
            courtId: court.id,
            startDate,
            endDate,
            attempted: totalAttempted,
            generated: inserted,
            skipped: totalAttempted - inserted,
          },
        });
      }

      return inserted;
    });

    return {
      generated,
      // populated-date skips + any race-condition dedupes from the DB
      skipped: skipped + (totalAttempted - generated),
    };
  }

  // --------------------------------------------------------------------------
  // Reads
  // --------------------------------------------------------------------------

  /**
   * List slots for the current tenant with filtering and pagination.
   * Expired holds are lazily released before the query so availability is
   * always reported as of "now".
   */
  async findAll(
    tenantId: string,
    query: QuerySlotsDto,
  ): Promise<SlotListResponse> {
    await this.releaseExpiredHolds(tenantId);

    const { courtId, status, date, page = 1, limit = 20 } = query;
    const skip = (page - 1) * limit;

    const where: Prisma.SlotWhereInput = { tenantId, deletedAt: null };
    if (courtId) where.courtId = courtId;
    if (status) where.status = status;
    if (date) where.date = this.parseDateString(date);

    const [slots, total] = await Promise.all([
      this.prisma.slot.findMany({
        where,
        include: { court: { select: { name: true } } },
        orderBy: [{ date: 'asc' }, { startTime: 'asc' }],
        skip,
        take: limit,
      }),
      this.prisma.slot.count({ where }),
    ]);

    return {
      data: slots.map((slot) => this.transformSlot(slot)),
      total,
      page,
      limit,
      totalPages: Math.ceil(total / limit) || 0,
    };
  }

  /**
   * Get a single slot by ID (tenant-scoped).
   */
  async findOne(id: string, tenantId: string): Promise<SlotResponse> {
    await this.releaseExpiredHolds(tenantId);

    const slot = await this.prisma.slot.findFirst({
      where: { id, tenantId, deletedAt: null },
      include: { court: { select: { name: true } } },
    });

    if (!slot) {
      throw new NotFoundException('Slot not found');
    }

    return this.transformSlot(slot);
  }

  // --------------------------------------------------------------------------
  // Hold lifecycle (checkout)
  // --------------------------------------------------------------------------

  /**
   * Temporarily hold an available slot during checkout.
   *
   * Uses a conditional `updateMany` so the transition Available → Held is
   * atomic at the DB level: concurrent hold requests cannot both succeed.
   * Throws 404 if the slot does not exist (in tenant) or 409 if it is not
   * currently available.
   */
  async holdSlot(
    tenantId: string,
    slotId: string,
    userId: string,
    holdMinutes: number = DEFAULT_HOLD_MINUTES,
  ): Promise<SlotResponse> {
    const now = new Date();
    const heldUntil = new Date(now.getTime() + holdMinutes * 60 * 1000);

    const slot = await this.prisma.$transaction(async (tx) => {
      const updated = await tx.slot.updateMany({
        where: { id: slotId, tenantId, status: SlotStatus.Available },
        data: {
          status: SlotStatus.Held,
          heldAt: now,
          heldBy: userId,
          heldUntil,
        },
      });

      if (updated.count === 0) {
        await this.assertSlotExists(tx, slotId, tenantId);
        throw new ConflictException('Slot is not available to hold');
      }

      const refreshed = await tx.slot.findFirst({
        where: { id: slotId, tenantId },
        include: { court: { select: { name: true } } },
      });
      await this.createAuditLog(tx, {
        tenantId,
        userId,
        entityType: 'Slot',
        entityId: slotId,
        action: 'Update',
        newValue: { status: SlotStatus.Held, heldBy: userId, heldUntil },
      });
      return refreshed!;
    });

    return this.transformSlot(slot);
  }

  /**
   * Release a held slot back to Available.
   */
  async releaseSlotHold(
    tenantId: string,
    slotId: string,
    userId: string,
  ): Promise<SlotResponse> {
    const slot = await this.prisma.$transaction(async (tx) => {
      const updated = await tx.slot.updateMany({
        where: { id: slotId, tenantId, status: SlotStatus.Held },
        data: {
          status: SlotStatus.Available,
          heldAt: null,
          heldBy: null,
          heldUntil: null,
        },
      });

      if (updated.count === 0) {
        await this.assertSlotExists(tx, slotId, tenantId);
        throw new ConflictException('Slot is not currently held');
      }

      const refreshed = await tx.slot.findFirst({
        where: { id: slotId, tenantId },
        include: { court: { select: { name: true } } },
      });
      await this.createAuditLog(tx, {
        tenantId,
        userId,
        entityType: 'Slot',
        entityId: slotId,
        action: 'Update',
        newValue: { status: SlotStatus.Available, released: true },
      });
      return refreshed!;
    });

    return this.transformSlot(slot);
  }

  // --------------------------------------------------------------------------
  // Block / Unblock (maintenance, private events)
  // --------------------------------------------------------------------------

  /**
   * Block an Available or Held slot (e.g. for maintenance). A reason is
   * recorded for the audit trail. Already-booked slots cannot be blocked.
   */
  async blockSlot(
    tenantId: string,
    slotId: string,
    userId: string,
    reason: string,
  ): Promise<SlotResponse> {
    const slot = await this.prisma.$transaction(async (tx) => {
      const updated = await tx.slot.updateMany({
        where: {
          id: slotId,
          tenantId,
          status: { in: [SlotStatus.Available, SlotStatus.Held] },
        },
        data: {
          status: SlotStatus.Blocked,
          heldAt: null,
          heldBy: null,
          heldUntil: null,
        },
      });

      if (updated.count === 0) {
        await this.assertSlotExists(tx, slotId, tenantId);
        throw new ConflictException(
          'Slot cannot be blocked (it is already booked or blocked)',
        );
      }

      const refreshed = await tx.slot.findFirst({
        where: { id: slotId, tenantId },
        include: { court: { select: { name: true } } },
      });
      await this.createAuditLog(tx, {
        tenantId,
        userId,
        entityType: 'Slot',
        entityId: slotId,
        action: 'Update',
        newValue: { status: SlotStatus.Blocked, reason },
      });
      return refreshed!;
    });

    return this.transformSlot(slot);
  }

  /**
   * Unblock a slot, returning it to Available.
   */
  async unblockSlot(
    tenantId: string,
    slotId: string,
    userId: string,
  ): Promise<SlotResponse> {
    const slot = await this.prisma.$transaction(async (tx) => {
      const updated = await tx.slot.updateMany({
        where: { id: slotId, tenantId, status: SlotStatus.Blocked },
        data: { status: SlotStatus.Available },
      });

      if (updated.count === 0) {
        await this.assertSlotExists(tx, slotId, tenantId);
        throw new ConflictException('Slot is not currently blocked');
      }

      const refreshed = await tx.slot.findFirst({
        where: { id: slotId, tenantId },
        include: { court: { select: { name: true } } },
      });
      await this.createAuditLog(tx, {
        tenantId,
        userId,
        entityType: 'Slot',
        entityId: slotId,
        action: 'Update',
        newValue: { status: SlotStatus.Available, unblocked: true },
      });
      return refreshed!;
    });

    return this.transformSlot(slot);
  }

  // --------------------------------------------------------------------------
  // Booking integration (internal — NOT exposed via REST by this module)
  // --------------------------------------------------------------------------

  /**
   * Mark a slot as Booked. Intended to be called by the Bookings module when a
   * booking is confirmed; it accepts an optional transaction client so it can
   * run inside the caller's transaction. This module exposes no HTTP route for
   * it — bookings own that lifecycle.
   *
   * Race-safe: the conditional `updateMany` only transitions Available|Held.
   */
  async bookSlot(
    tenantId: string,
    slotId: string,
    tx?: PrismaTransaction,
  ): Promise<void> {
    const client = tx ?? this.prisma;
    const updated = await client.slot.updateMany({
      where: {
        id: slotId,
        tenantId,
        status: { in: [SlotStatus.Available, SlotStatus.Held] },
      },
      data: {
        status: SlotStatus.Booked,
        heldAt: null,
        heldBy: null,
        heldUntil: null,
      },
    });

    if (updated.count === 0) {
      await this.assertSlotExists(client, slotId, tenantId);
      throw new ConflictException('Slot is not available to book');
    }
  }

  // --------------------------------------------------------------------------
  // Cleanup
  // --------------------------------------------------------------------------

  /**
   * Hard-delete stale slots strictly before `beforeDate`.
   *
   * RATIONALE: slots are regenerable inventory derived from pricing rules, so
   * soft-deleting past availability only bloats the `@@index([tenantId,
   * status, date])`. Hard deletion keeps the table lean. To stay safe we only
   * remove slots that are NOT booked and have NO booking referencing them
   * (the `BookingSlot.slotId` FK is restrict, and booked history must be kept).
   *
   * @returns the number of slots deleted
   */
  async cleanupExpired(
    tenantId: string,
    beforeDate: string,
    userId: string,
  ): Promise<{ deleted: number }> {
    const before = this.parseDateString(beforeDate);
    if (Number.isNaN(before.getTime())) {
      throw new BadRequestException('Invalid beforeDate format');
    }

    const deleted = await this.prisma.$transaction(async (tx) => {
      const result = await tx.slot.deleteMany({
        where: {
          tenantId,
          date: { lt: before },
          status: { not: SlotStatus.Booked },
          bookingSlots: { none: {} },
        },
      });

      await this.createAuditLog(tx, {
        tenantId,
        userId,
        entityType: 'Slot',
        entityId: tenantId,
        action: 'Delete',
        oldValue: { beforeDate, deleted: result.count },
      });

      return result.count;
    });

    return { deleted };
  }

  // --------------------------------------------------------------------------
  // Settings & Holidays
  // --------------------------------------------------------------------------

  /**
   * Get the tenant's slot-generation settings (weekend days, timezone,
   * auto-generation configuration).
   */
  async getSlotSettings(tenantId: string): Promise<SlotSettingsResponse> {
    const tenant = await this.prisma.tenant.findUnique({
      where: { id: tenantId },
      select: {
        timezone: true,
        weekendDays: true,
        autoGenerateEnabled: true,
        autoGenerateDaysAhead: true,
      },
    });
    if (!tenant) {
      throw new NotFoundException('Tenant not found');
    }

    return {
      weekendDays: this.parseWeekendDays(tenant.weekendDays),
      timezone: tenant.timezone,
      autoGenerateEnabled: tenant.autoGenerateEnabled,
      autoGenerateDaysAhead: tenant.autoGenerateDaysAhead,
    };
  }

  /**
   * Update the tenant's slot-generation settings. Written to the Tenant row
   * with an audit entry in the same transaction.
   */
  async updateSlotSettings(
    tenantId: string,
    dto: UpdateSlotSettingsDto,
    userId: string,
  ): Promise<SlotSettingsResponse> {
    const existing = await this.prisma.tenant.findUnique({
      where: { id: tenantId },
      select: {
        timezone: true,
        weekendDays: true,
        autoGenerateEnabled: true,
        autoGenerateDaysAhead: true,
      },
    });
    if (!existing) {
      throw new NotFoundException('Tenant not found');
    }

    const data: Prisma.TenantUpdateInput = {};
    if (dto.weekendDays !== undefined) {
      data.weekendDays = dto.weekendDays;
    }
    if (dto.autoGenerateEnabled !== undefined) {
      data.autoGenerateEnabled = dto.autoGenerateEnabled;
    }
    if (dto.autoGenerateDaysAhead !== undefined) {
      data.autoGenerateDaysAhead = dto.autoGenerateDaysAhead;
    }

    await this.prisma.$transaction(async (tx) => {
      await tx.tenant.update({ where: { id: tenantId }, data });

      await this.createAuditLog(tx, {
        tenantId,
        userId,
        entityType: 'Tenant',
        entityId: tenantId,
        action: 'Update',
        oldValue: {
          weekendDays: existing.weekendDays,
          autoGenerateEnabled: existing.autoGenerateEnabled,
          autoGenerateDaysAhead: existing.autoGenerateDaysAhead,
        },
        newValue: {
          weekendDays: dto.weekendDays ?? existing.weekendDays,
          autoGenerateEnabled:
            dto.autoGenerateEnabled ?? existing.autoGenerateEnabled,
          autoGenerateDaysAhead:
            dto.autoGenerateDaysAhead ?? existing.autoGenerateDaysAhead,
        },
      });
    });

    return {
      weekendDays:
        dto.weekendDays ?? this.parseWeekendDays(existing.weekendDays),
      timezone: existing.timezone,
      autoGenerateEnabled:
        dto.autoGenerateEnabled ?? existing.autoGenerateEnabled,
      autoGenerateDaysAhead:
        dto.autoGenerateDaysAhead ?? existing.autoGenerateDaysAhead,
    };
  }

  /**
   * List the tenant's holiday calendar. Dates marked as holidays are priced
   * with Holiday pricing rules (or generate no slots if none exist).
   */
  async listHolidays(tenantId: string): Promise<HolidayResponse[]> {
    const holidays = await this.prisma.holiday.findMany({
      where: { tenantId },
      orderBy: { date: 'asc' },
    });
    return holidays.map((h) => ({
      id: h.id,
      tenantId: h.tenantId,
      date: this.formatDateToYYYYMMDD(h.date),
      name: h.name,
    }));
  }

  /**
   * Mark a date as a holiday. One holiday per (tenant, date) — a duplicate
   * date returns 409.
   */
  async addHoliday(
    tenantId: string,
    dto: CreateHolidayDto,
    userId: string,
  ): Promise<HolidayResponse> {
    const date = this.parseDateString(dto.date);
    if (Number.isNaN(date.getTime())) {
      throw new BadRequestException('Invalid date format');
    }

    const duplicate = await this.prisma.holiday.findFirst({
      where: { tenantId, date },
      select: { id: true },
    });
    if (duplicate) {
      throw new ConflictException('A holiday is already marked for this date');
    }

    const created = await this.prisma.$transaction(async (tx) => {
      const holiday = await tx.holiday.create({
        data: { tenantId, date, name: dto.name },
      });

      await this.createAuditLog(tx, {
        tenantId,
        userId,
        entityType: 'Holiday',
        entityId: holiday.id,
        action: 'Create',
        newValue: { date: dto.date, name: dto.name },
      });

      return holiday;
    });

    return {
      id: created.id,
      tenantId: created.tenantId,
      date: this.formatDateToYYYYMMDD(created.date),
      name: created.name,
    };
  }

  /**
   * Remove a holiday from the tenant's calendar. Future generation runs will
   * classify the date by its weekday again; already-generated slots keep
   * their price snapshots.
   */
  async removeHoliday(
    tenantId: string,
    holidayId: string,
    userId: string,
  ): Promise<{ message: string }> {
    const holiday = await this.prisma.holiday.findFirst({
      where: { id: holidayId, tenantId },
    });
    if (!holiday) {
      throw new NotFoundException('Holiday not found');
    }

    await this.prisma.$transaction(async (tx) => {
      await tx.holiday.delete({ where: { id: holidayId } });

      await this.createAuditLog(tx, {
        tenantId,
        userId,
        entityType: 'Holiday',
        entityId: holidayId,
        action: 'Delete',
        oldValue: {
          date: this.formatDateToYYYYMMDD(holiday.date),
          name: holiday.name,
        },
      });
    });

    return { message: 'Holiday removed successfully' };
  }

  /**
   * Lazily release holds whose `heldUntil` has passed. Cheaper and simpler
   * than a cron job for v1; called before every read.
   *
   * NOTE: a dedicated `@Cron` job (the task's "Option A") can be added later
   * to release holds even when the slots table is not being read.
   *
   * Public: BookingsService.getDayView calls this lazily before reading the
   * day grid, mirroring findAll/findOne here.
   */
  async releaseExpiredHolds(tenantId: string): Promise<void> {
    await this.prisma.slot.updateMany({
      where: {
        tenantId,
        status: SlotStatus.Held,
        heldUntil: { lt: new Date() },
      },
      data: {
        status: SlotStatus.Available,
        heldAt: null,
        heldBy: null,
        heldUntil: null,
      },
    });
  }

  // ==========================================================================
  // Private Helpers
  // ==========================================================================

  /**
   * Throw 404 if a tenant-scoped slot does not exist. Used to distinguish
   * "not found" from "wrong state" after a zero-row conditional update.
   */
  private async assertSlotExists(
    client: PrismaTransaction,
    slotId: string,
    tenantId: string,
  ): Promise<void> {
    const exists = await client.slot.findFirst({
      where: { id: slotId, tenantId },
    });
    if (!exists) {
      throw new NotFoundException('Slot not found');
    }
  }

  /**
   * Parse a `YYYY-MM-DD` string into a UTC-midnight Date. Pinning to UTC keeps
   * day-type determination (and the stored `@db.Date` value) deterministic
   * regardless of the server's local timezone.
   */
  private parseDateString(dateStr: string): Date {
    const [year, month, day] = dateStr.split('-').map(Number);
    return new Date(Date.UTC(year, month - 1, day));
  }

  /**
   * Format a `@db.Date` Date as `YYYY-MM-DD` using UTC getters.
   */
  private formatDateToYYYYMMDD(date: Date): string {
    const year = date.getUTCFullYear();
    const month = (date.getUTCMonth() + 1).toString().padStart(2, '0');
    const day = date.getUTCDate().toString().padStart(2, '0');
    return `${year}-${month}-${day}`;
  }

  /**
   * Format a `@db.Time` Date as `HH:mm` using UTC getters (symmetric with
   * parseTimeString).
   */
  private formatTimeToHHmm(date: Date): string {
    const hours = date.getUTCHours().toString().padStart(2, '0');
    const minutes = date.getUTCMinutes().toString().padStart(2, '0');
    return `${hours}:${minutes}`;
  }

  /**
   * Iterate every UTC day in an inclusive [start, end] range.
   */
  private eachDay(start: Date, end: Date): Date[] {
    const days: Date[] = [];
    const MS_PER_DAY = 24 * 60 * 60 * 1000;
    for (let t = start.getTime(); t <= end.getTime(); t += MS_PER_DAY) {
      days.push(new Date(t));
    }
    return days;
  }

  /**
   * Determine the day type for a date, in priority order:
   *   1. Holiday — the date is in the tenant's holiday calendar
   *   2. Weekend — the date's weekday (in the TENANT's timezone) is one of the
   *      tenant's configured weekend days (default Fri + Sat for Bangladesh)
   *   3. Weekday
   *
   * The weekday is evaluated by probing the date at 12:00 UTC — noon UTC falls
   * on the same calendar date in every real timezone — and formatting it in
   * the tenant's timezone, so classification matches the tenant's local
   * calendar rather than the server's.
   */
  private getDayType(
    date: Date,
    weekendDays: number[],
    holidayDates: Set<string>,
    timezone: string,
  ): DayType {
    const dateStr = this.formatDateToYYYYMMDD(date);

    if (holidayDates.has(dateStr)) {
      return DayType.Holiday;
    }

    const probe = new Date(`${dateStr}T12:00:00Z`);
    const weekdayName = this.getWeekdayFormatter(timezone).format(probe);
    const weekdayIndex = WEEKDAY_NAME_TO_INDEX[weekdayName] ?? -1;

    if (weekendDays.includes(weekdayIndex)) {
      return DayType.Weekend;
    }
    return DayType.Weekday;
  }

  /**
   * Intl weekday formatters cached per timezone (building an Intl formatter
   * is expensive; generation classifies many dates per call).
   */
  private readonly weekdayFormatters = new Map<string, Intl.DateTimeFormat>();

  private getWeekdayFormatter(timezone: string): Intl.DateTimeFormat {
    let formatter = this.weekdayFormatters.get(timezone);
    if (!formatter) {
      formatter = new Intl.DateTimeFormat('en-US', {
        timeZone: timezone,
        weekday: 'short',
      });
      this.weekdayFormatters.set(timezone, formatter);
    }
    return formatter;
  }

  /**
   * Parse the tenant's `weekendDays` JSON value into ISO weekday ints.
   * Falls back to the Bangladesh weekend (Fri + Sat) on any invalid value.
   */
  private parseWeekendDays(raw: unknown): number[] {
    if (Array.isArray(raw)) {
      const days = raw.filter(
        (d): d is number =>
          typeof d === 'number' && Number.isInteger(d) && d >= 0 && d <= 6,
      );
      if (days.length > 0) {
        return days;
      }
    }
    return DEFAULT_WEEKEND_DAYS;
  }

  /**
   * Current calendar date (YYYY-MM-DD) as experienced in the given timezone.
   * 'en-CA' locale formats as YYYY-MM-DD.
   */
  private todayInTimezone(timezone: string): string {
    return new Intl.DateTimeFormat('en-CA', {
      timeZone: timezone,
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
    }).format(new Date());
  }

  /**
   * Add whole days to a YYYY-MM-DD string (UTC arithmetic; date-only values
   * have no DST concerns).
   */
  private addDaysToDateString(dateStr: string, days: number): string {
    const date = this.parseDateString(dateStr);
    date.setUTCDate(date.getUTCDate() + days);
    return this.formatDateToYYYYMMDD(date);
  }

  /**
   * Expand a pricing rule's [startTime, endTime] into consecutive
   * fixed-interval slots (e.g. 60, 90 or 120 minutes). A trailing partial
   * window is dropped: the last slot only exists if it fits fully inside the
   * rule window. `endTime` is an exclusive upper bound, matching how the
   * Pricing module stores inclusive end times (including the +24h midnight
   * case, which is already resolved by the time it is read back).
   */
  private generateIntervalSlots(
    ruleStartTime: Date,
    ruleEndTime: Date,
    intervalMinutes: number,
  ): Array<{ startTime: Date; endTime: Date }> {
    const slots: Array<{ startTime: Date; endTime: Date }> = [];
    const step = intervalMinutes * 60 * 1000;
    const startMs = ruleStartTime.getTime();
    const endMs = ruleEndTime.getTime();

    for (let t = startMs; t + step <= endMs; t += step) {
      slots.push({ startTime: new Date(t), endTime: new Date(t + step) });
    }

    return slots;
  }

  /**
   * Transform a Prisma slot (with optional court name) into the API shape.
   */
  private transformSlot(
    slot: Slot & { court?: { name: string } | null },
  ): SlotResponse {
    const { court, ...data } = slot;
    return {
      id: data.id,
      tenantId: data.tenantId,
      courtId: data.courtId,
      courtName: court?.name ?? undefined,
      pricingRuleId: data.pricingRuleId ?? undefined,
      price: data.price.toString(),
      date: this.formatDateToYYYYMMDD(data.date),
      startTime: this.formatTimeToHHmm(data.startTime),
      endTime: this.formatTimeToHHmm(data.endTime),
      status: data.status,
      heldAt: data.heldAt,
      heldBy: data.heldBy,
      heldUntil: data.heldUntil,
      createdAt: data.createdAt,
      updatedAt: data.updatedAt,
    };
  }

  /**
   * Write an audit-log row using the provided transaction client.
   */
  private async createAuditLog(
    tx: PrismaTransaction,
    data: {
      tenantId: string;
      userId: string;
      entityType: string;
      entityId: string;
      action: string;
      oldValue?: Record<string, unknown>;
      newValue?: Record<string, unknown>;
    },
  ): Promise<void> {
    await tx.auditLog.create({
      data: {
        tenantId: data.tenantId,
        userId: data.userId,
        entityType: data.entityType as any,
        entityId: data.entityId,
        action: data.action as any,
        oldValue: data.oldValue as Prisma.InputJsonValue,
        newValue: data.newValue as Prisma.InputJsonValue,
      },
    });
  }
}
