import { ApiProperty } from '@nestjs/swagger';
import {
  IsArray,
  IsBoolean,
  IsInt,
  IsOptional,
  IsString,
  Max,
  Min,
  IsIn,
} from 'class-validator';
import { Type } from 'class-transformer';

/**
 * ISO weekday numbers (0 = Sunday … 6 = Saturday) that can be marked as
 * weekend days for a tenant.
 */
export const WEEKDAY_INDICES = [0, 1, 2, 3, 4, 5, 6];

export class UpdateSlotSettingsDto {
  @ApiProperty({
    description:
      'ISO weekday numbers treated as weekend days (0 = Sunday … 6 = Saturday). ' +
      'Defaults to [5, 6] (Friday + Saturday, the Bangladesh weekend).',
    example: [5, 6],
    required: false,
  })
  @IsArray()
  @IsIn(WEEKDAY_INDICES, {
    each: true,
    message: 'Each weekend day must be an integer between 0 (Sun) and 6 (Sat)',
  })
  @IsOptional()
  weekendDays?: number[];

  @ApiProperty({
    description:
      'When enabled, a scheduler generates slots for all courts automatically',
    example: true,
    required: false,
  })
  @IsBoolean()
  @IsOptional()
  autoGenerateEnabled?: boolean;

  @ApiProperty({
    description:
      'How many days ahead the auto-generation scheduler keeps slots generated',
    example: 14,
    required: false,
  })
  @Type(() => Number)
  @IsInt()
  @Min(1, { message: 'Days ahead must be at least 1' })
  @Max(90, { message: 'Days ahead cannot exceed 90' })
  @IsOptional()
  autoGenerateDaysAhead?: number;
}

export class SlotSettingsResponseDto {
  @ApiProperty({
    description: 'ISO weekday numbers configured as weekend days',
    example: [5, 6],
  })
  weekendDays!: number[];

  @ApiProperty({
    description: "Tenant's timezone (IANA name) used for day classification",
    example: 'Asia/Dhaka',
  })
  @IsString()
  timezone!: string;

  @ApiProperty({
    description: 'Whether automatic slot generation is enabled',
    example: false,
  })
  autoGenerateEnabled!: boolean;

  @ApiProperty({
    description: 'Days ahead the scheduler generates slots for',
    example: 14,
  })
  autoGenerateDaysAhead!: number;
}
