"use client";

/**
 * Empty-day state for the calendar (slots.length === 0).
 *
 * Two branches (Task 5 spec):
 *  1. Date beyond the auto-generation horizon → "Generate slots" CTA that
 *     runs the existing slot generation for this single date. Cross-module
 *     invalidation of the bookings day-view lives HERE, not in
 *     hooks/slots.ts (repo convention: hooks invalidate their own module).
 *  2. Date within the horizon but empty → pricing rules likely don't cover
 *     it → pointer to /dashboard/pricing-rules. Past empty dates get a
 *     neutral copy (nothing to generate retroactively... generation does
 *     work for past dates, but there's no operational reason to).
 */

import { useMemo } from "react";
import Link from "next/link";
import { useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { CalendarOff, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useGenerateSlots, useSlotSettings } from "@/hooks/slots";
import { bookingKeys } from "@/hooks/bookings";
import { isoDiffDays } from "./grid-utils";

export function EmptyDayState({
  date,
  todayIso,
}: {
  date: string;
  todayIso: string;
}) {
  const queryClient = useQueryClient();
  const { data: settings, isLoading: settingsLoading } = useSlotSettings();
  const generate = useGenerateSlots();

  const daysAhead = settings?.autoGenerateDaysAhead ?? 14;
  const beyondHorizon = useMemo(
    () => isoDiffDays(todayIso, date) > daysAhead,
    [todayIso, date, daysAhead],
  );
  const isPastDate = date < todayIso;

  return (
    <div className="flex flex-col items-center justify-center gap-3 rounded-xl border border-dashed bg-card/50 px-6 py-16 text-center">
      <div className="flex h-10 w-10 items-center justify-center rounded-full bg-muted">
        <CalendarOff className="h-5 w-5 text-muted-foreground" />
      </div>

      {beyondHorizon && !isPastDate ? (
        <>
          <div className="space-y-1">
            <p className="text-sm font-semibold text-foreground">
              No slots for this date yet
            </p>
            <p className="text-xs text-muted-foreground">
              {date} is beyond your {daysAhead}-day generation horizon.
            </p>
          </div>
          <Button
            size="sm"
            className="gap-1.5 bg-teal-600 text-xs hover:bg-teal-700"
            disabled={generate.isPending || settingsLoading}
            onClick={() =>
              generate.mutate(
                { startDate: date, endDate: date },
                {
                  onSuccess: (result) => {
                    // Cross-module: generation changes what the calendar shows.
                    queryClient.invalidateQueries({
                      queryKey: bookingKeys.dayViews(),
                    });
                    if (result.generated > 0) {
                      toast.success(`Generated ${result.generated} slots`, {
                        description: date,
                      });
                    } else {
                      toast.info("No new slots generated", {
                        description:
                          "Pricing rules may not cover this date — check the pricing page.",
                      });
                    }
                  },
                  onError: (error) => {
                    toast.error("Failed to generate slots", {
                      description: error.message,
                    });
                  },
                },
              )
            }
          >
            <Sparkles className="h-4 w-4" />
            {generate.isPending ? "Generating…" : "Generate slots"}
          </Button>
        </>
      ) : (
        <>
          <div className="space-y-1">
            <p className="text-sm font-semibold text-foreground">
              {isPastDate
                ? "No slots were generated for this date"
                : "No slots yet — pricing rules may be missing"}
            </p>
            <p className="text-xs text-muted-foreground">
              {isPastDate
                ? "Past dates can't be booked."
                : "Slots are generated from pricing rules for each court."}
            </p>
          </div>
          {!isPastDate && (
            <Button asChild variant="outline" size="sm" className="text-xs">
              <Link href="/dashboard/pricing-rules">Review pricing rules</Link>
            </Button>
          )}
        </>
      )}
    </div>
  );
}
