"use client";

import { useState } from "react";
import { Bot, CalendarPlus, Loader2, X } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import {
  useSlotSettings,
  useUpdateSlotSettings,
  useHolidays,
  useAddHoliday,
  useRemoveHoliday,
} from "@/hooks/slots";
import { WEEKDAY_LABELS } from "@/lib/types/slot";

/**
 * ISO weekday order with compact chip labels (Sunday-first, matching JS).
 */
const DAY_CHIPS = [
  { value: 0, label: "S" },
  { value: 1, label: "M" },
  { value: 2, label: "T" },
  { value: 3, label: "W" },
  { value: 4, label: "T" },
  { value: 5, label: "F" },
  { value: 6, label: "S" },
];

function formatDate(dateStr: string): string {
  const [y, m, d] = dateStr.split("-").map(Number);
  return new Date(y, m - 1, d).toLocaleDateString(undefined, {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

/**
 * Auto-pilot + day-type settings for slot generation.
 *
 * Makes the previously invisible day-type rules visible and editable:
 * - Which weekdays count as the weekend (default Fri + Sat for Bangladesh)
 * - Auto-generation: slots are kept generated N days ahead, no manual work
 * - The holiday calendar used for holiday pricing
 */
export function SlotSettingsCard() {
  const { data: settings, isLoading } = useSlotSettings();
  const updateSettings = useUpdateSlotSettings();

  const { data: holidays } = useHolidays();
  const addHoliday = useAddHoliday();
  const removeHoliday = useRemoveHoliday();

  const [holidayDate, setHolidayDate] = useState("");
  const [holidayName, setHolidayName] = useState("");

  const weekendDays = settings?.weekendDays ?? [5, 6];

  const handleToggleWeekendDay = (day: number) => {
    const next = weekendDays.includes(day)
      ? weekendDays.filter((d) => d !== day)
      : [...weekendDays, day].sort((a, b) => a - b);

    if (next.length === 0) {
      toast.error("At least one day must be a weekday");
      return;
    }

    updateSettings.mutate(
      { weekendDays: next },
      {
        onSuccess: () => {
          toast.success("Weekend days updated", {
            description: next.map((d) => WEEKDAY_LABELS[d]).join(", "),
          });
        },
        onError: (error: Error) => {
          toast.error("Failed to update weekend days", {
            description: error.message,
          });
        },
      },
    );
  };

  const handleToggleAutoGenerate = (enabled: boolean) => {
    updateSettings.mutate(
      { autoGenerateEnabled: enabled },
      {
        onSuccess: () => {
          toast.success(
            enabled ? "Auto-pilot enabled" : "Auto-pilot disabled",
            {
              description: enabled
                ? "Slots will be generated automatically, every hour."
                : "Generate slots manually from now on.",
            },
          );
        },
        onError: (error: Error) => {
          toast.error("Failed to update auto-pilot", {
            description: error.message,
          });
        },
      },
    );
  };

  const handleDaysAheadChange = (value: string) => {
    const days = Number(value);
    if (!Number.isInteger(days) || days < 1 || days > 90) {
      toast.error("Days ahead must be between 1 and 90");
      return;
    }
    if (days === settings?.autoGenerateDaysAhead) return;

    updateSettings.mutate(
      { autoGenerateDaysAhead: days },
      {
        onSuccess: () => {
          toast.success("Window updated", {
            description: `Slots are kept generated ${days} days ahead.`,
          });
        },
        onError: (error: Error) => {
          toast.error("Failed to update window", { description: error.message });
        },
      },
    );
  };

  const handleAddHoliday = (e: React.FormEvent) => {
    e.preventDefault();
    if (!holidayDate || !holidayName.trim()) {
      toast.error("Pick a date and give the holiday a name");
      return;
    }

    addHoliday.mutate(
      { date: holidayDate, name: holidayName.trim() },
      {
        onSuccess: () => {
          toast.success("Holiday added", {
            description: `${holidayName.trim()} on ${formatDate(holidayDate)}`,
          });
          setHolidayDate("");
          setHolidayName("");
        },
        onError: (error: Error) => {
          toast.error("Failed to add holiday", { description: error.message });
        },
      },
    );
  };

  const handleRemoveHoliday = (id: string, name: string) => {
    removeHoliday.mutate(id, {
      onSuccess: () => {
        toast.success("Holiday removed", { description: name });
      },
      onError: (error: Error) => {
        toast.error("Failed to remove holiday", { description: error.message });
      },
    });
  };

  if (isLoading || !settings) {
    return (
      <Card>
        <CardContent className="p-4 flex items-center gap-2 text-xs text-muted-foreground">
          <Loader2 className="h-4 w-4 animate-spin" />
          Loading generation settings...
        </CardContent>
      </Card>
    );
  }

  const isMutating = updateSettings.isPending;

  return (
    <div className="grid gap-4 lg:grid-cols-2">
      {/* Auto-pilot + weekend days */}
      <Card className="border-teal-200/30 bg-teal-50/30 dark:border-teal-900/50 dark:bg-teal-950/20">
        <CardContent className="p-4 space-y-4">
          <div className="flex items-start justify-between gap-3">
            <div className="flex items-start gap-2">
              <div className="h-8 w-8 rounded-full bg-teal-600/10 flex items-center justify-center shrink-0">
                <Bot className="h-4 w-4 text-teal-600" />
              </div>
              <div>
                <p className="text-xs font-semibold text-foreground">
                  Auto-pilot
                </p>
                <p className="text-[11px] text-muted-foreground mt-0.5">
                  Keep slots generated automatically — no manual generation
                  needed.
                </p>
              </div>
            </div>
            <Switch
              checked={settings.autoGenerateEnabled}
              onCheckedChange={handleToggleAutoGenerate}
              disabled={isMutating}
              aria-label="Toggle auto-generation"
            />
          </div>

          <div
            className={
              settings.autoGenerateEnabled ? "space-y-3" : "space-y-3 opacity-60"
            }
          >
            <div className="flex items-center justify-between gap-3">
              <Label
                htmlFor="daysAhead"
                className="text-[11px] text-muted-foreground"
              >
                Keep slots generated (days ahead)
              </Label>
              <Input
                id="daysAhead"
                type="number"
                min={1}
                max={90}
                defaultValue={settings.autoGenerateDaysAhead}
                onBlur={(e) => handleDaysAheadChange(e.target.value)}
                disabled={isMutating || !settings.autoGenerateEnabled}
                className="w-20 h-8 text-xs"
              />
            </div>

            <div className="space-y-1.5">
              <p className="text-[11px] text-muted-foreground">
                Weekend days (priced with weekend rates)
              </p>
              <div className="flex gap-1">
                {DAY_CHIPS.map((chip) => {
                  const active = weekendDays.includes(chip.value);
                  return (
                    <button
                      key={chip.value}
                      type="button"
                      title={WEEKDAY_LABELS[chip.value]}
                      onClick={() => handleToggleWeekendDay(chip.value)}
                      disabled={isMutating}
                      className={
                        active
                          ? "h-7 w-7 rounded-md bg-teal-600 text-white text-[11px] font-semibold transition-colors hover:bg-teal-700"
                          : "h-7 w-7 rounded-md bg-card border text-[11px] text-muted-foreground transition-colors hover:bg-muted"
                      }
                    >
                      {chip.label}
                    </button>
                  );
                })}
              </div>
              <p className="text-[10px] text-muted-foreground">
                Timezone: {settings.timezone}. Tap a day to toggle it.
              </p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Holidays */}
      <Card>
        <CardContent className="p-4 space-y-3">
          <div className="flex items-start gap-2">
            <div className="h-8 w-8 rounded-full bg-purple-600/10 flex items-center justify-center shrink-0">
              <CalendarPlus className="h-4 w-4 text-purple-600" />
            </div>
            <div>
              <p className="text-xs font-semibold text-foreground">
                Holidays
              </p>
              <p className="text-[11px] text-muted-foreground mt-0.5">
                These dates use holiday pricing (or stay closed if no holiday
                rates exist).
              </p>
            </div>
          </div>

          <form
            onSubmit={handleAddHoliday}
            className="flex items-end gap-2"
          >
            <div className="flex-1 space-y-1">
              <Label
                htmlFor="holidayDate"
                className="text-[10px] text-muted-foreground"
              >
                Date
              </Label>
              <Input
                id="holidayDate"
                type="date"
                value={holidayDate}
                onChange={(e) => setHolidayDate(e.target.value)}
                className="h-8 text-xs"
                disabled={addHoliday.isPending}
              />
            </div>
            <div className="flex-2 space-y-1">
              <Label
                htmlFor="holidayName"
                className="text-[10px] text-muted-foreground"
              >
                Name
              </Label>
              <Input
                id="holidayName"
                placeholder="e.g. Eid Day 1"
                value={holidayName}
                onChange={(e) => setHolidayName(e.target.value)}
                maxLength={100}
                className="h-8 text-xs"
                disabled={addHoliday.isPending}
              />
            </div>
            <Button
              type="submit"
              size="sm"
              className="h-8 text-xs"
              disabled={addHoliday.isPending}
            >
              {addHoliday.isPending ? (
                <Loader2 className="h-3.5 w-3.5 animate-spin" />
              ) : (
                "Add"
              )}
            </Button>
          </form>

          <div className="max-h-36 space-y-1 overflow-y-auto">
            {(holidays ?? []).length === 0 ? (
              <p className="text-[11px] text-muted-foreground py-2">
                No holidays marked yet.
              </p>
            ) : (
              (holidays ?? []).map((holiday) => (
                <div
                  key={holiday.id}
                  className="flex items-center justify-between rounded-md border bg-card px-2.5 py-1.5"
                >
                  <div className="min-w-0">
                    <p className="text-xs font-medium text-foreground truncate">
                      {holiday.name}
                    </p>
                    <p className="text-[10px] text-muted-foreground">
                      {formatDate(holiday.date)}
                    </p>
                  </div>
                  <Button
                    type="button"
                    variant="ghost"
                    size="sm"
                    className="h-6 w-6 p-0 text-muted-foreground hover:text-destructive"
                    onClick={() =>
                      handleRemoveHoliday(holiday.id, holiday.name)
                    }
                    disabled={removeHoliday.isPending}
                    aria-label={`Remove ${holiday.name}`}
                  >
                    {removeHoliday.isPending ? (
                      <Loader2 className="h-3.5 w-3.5 animate-spin" />
                    ) : (
                      <X className="h-3.5 w-3.5" />
                    )}
                  </Button>
                </div>
              ))
            )}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
